
version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: postgresdb-util-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=agroleague
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 3333:8080